### ISSUE TITLE
readme with purpose missing

### ISSUE THREAD

**Issue by jogi-k** [johannrichard/tuya-shelly#1]
stumbled over the repo and it sounds interesting.
unfortunately its exact purpose is not clear...

* Is it a integration into homebridge?
* Is it something standalone?
* does it need the tuya cloud / hombli-app / ?
* does it work locally ?

So a small readme would be really great...

**Comment by johannrichard** [comment]
I'm afraid the codebase is mostly abandoned. I will probably move it to "archived", feel free to pick from it if you want. I've nevertheless added a `README.md` to explain a bit what I intended to achieve.
